CREATE TABLE IF NOT EXISTS game_sessions (
  id SERIAL PRIMARY KEY,
  won BOOLEAN NOT NULL,
  attempts INTEGER NOT NULL,
  max_attempts INTEGER NOT NULL,
  min_value INTEGER NOT NULL,
  max_value INTEGER NOT NULL,
  score INTEGER NOT NULL,
  played_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
